Option Explicit
' Launches the Kenney Asset Index with no console window.
' Generated by launcher/install-shortcut.ps1 -- edit that, not this.
Dim shell, fso, here, node, script
Set shell = CreateObject("WScript.Shell")
Set fso = CreateObject("Scripting.FileSystemObject")
here = fso.GetParentFolderName(WScript.ScriptFullName)
node = "C:\Program Files\nodejs\node.exe"
If Not fso.FileExists(node) Then node = "node.exe"
script = fso.BuildPath(here, "launch.mjs")
shell.CurrentDirectory = fso.GetParentFolderName(here)
shell.Run """" & node & """ """ & script & """", 0, False
